package com.water.water.model;

import jakarta.persistence.*;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import java.time.LocalDateTime;
import java.math.BigDecimal;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "bills")
public class Bill {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "household_id")
    private Household household;

    // Optional: for bills targeting a Community Admin directly (generated by Super Admin)
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "target_user_id")
    private User targetUser;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "billing_cycle_id", nullable = false)
    private BillingCycle billingCycle;

    @Column(name = "consumption_liters", nullable = false)
    private double consumptionLiters;

    @Column(nullable = false)
    private BigDecimal amount;

    @Column(name = "base_charge")
    private BigDecimal baseCharge = BigDecimal.ZERO;

    @Column(name = "excess_charge")
    private BigDecimal excessCharge = BigDecimal.ZERO;

    @Column(name = "shared_cost_allocation")
    private BigDecimal sharedCostAllocation = BigDecimal.ZERO;

    @Column(nullable = false)
    private boolean paid = false;

    @Column(name = "payment_date")
    private LocalDateTime paymentDate;

    @Column(name = "invoice_number", nullable = false)
    private String invoiceNumber;

    @Column(name = "razorpay_order_id")
    private String razorpayOrderId;

    @Column(name = "razorpay_payment_id")
    private String razorpayPaymentId;

    @Column(name = "razorpay_signature")
    private String razorpaySignature;
}
